music/api/urls.py
from django.conf.urls import url
from .views import AlbumsView,SongsView,AlbumView,SongsUrlView
urlpatterns = [
    url(r'^albums/$', AlbumsView.as_view(), name='albumsview'),
    url(r'^songs/(?P<album_id>[0-9]+)',SongsView.as_view(),name='songsview'),
    url(r'^songsurl/(?P<album_id>[0-9]+)',SongsUrlView.as_view(),name='songsview'),
    url(r'^album/(?P<pk>[0-9]+)/$', AlbumView.as_view(), name='albumsview'),
    
]

music/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^songs/$', views.songs, name='songs'),
    #url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^create_playlist/$',views.create_playlist, name = 'create_playlist'),
    url(r'^playlists/$',views.playlists,name = 'playlists'),
    url(r'^playlist/(?P<playlist_id>[0-9]+)/$',views.playlist,name='playlist'),
    url(r'^addsongtoplaylist/(?P<song_id>[0-9]+)/(?P<playlist_id>[0-9]+)',views.add_song_to_playlist,name='addsongtoplaylist'),
    url(r'^addalbumtoplaylist/(?P<album_id>[0-9]+)/(?P<playlist_id>[0-9]+)',views.add_album_to_playlist,name='addalbumtoplaylist'),
    url(r'^addsongstoplaylist/(?P<playlist_id>[0-9]+)',views.add_songs_to_playlist,name='addsongstoplaylist'),
    url(r'^deletesongfromplaylist/(?P<playlist_id>[0-9]+)/(?P<song_id>[0-9]+)',views.delete_song_from_playlist,name='deletesongfromplaylist'),
    url(r'^addalbumstoplaylist/(?P<playlist_id>[0-9]+)',views.add_albums_to_playlist,name='addalbumstoplaylist'),
    url(r'^deleteplaylist/(?P<playlist_id>[0-9]+)',views.delete_playlist,name = 'deleteplaylist'),
    url(r'^removeallsongsfromplaylist/(?P<playlist_id>[0-9]+)/(?P<typ>[0-9]+)',views.remove_allsongs_from_playlist,name = 'removeallsongsfromplaylist'),
    url(r'^renameplaylist/(?P<playlist_id>[0-9]+)',views.rename_playlist,name='rename_playlist'),
    url(r'^users/',views.users,name='users'),
    url(r'^viewuser/(?P<user_id>[0-9]+)',views.view_user,name = 'viewuser' ),
    url(r'^index2',views.index2,name='index2'),
    url(r'^search',views.search,name ='search'),
    url(r'^addalbums',views.addAlbums,name = 'addalbums'),
    url(r'^addgivenalbum/(?P<album_id>[0-9]+)',views.addGivenAlbum,name='addgivenalbum'),
    url(r'^myalbums',views.myAlbums,name = "myalbums"),
    url(r'^removegivenalbum/(?P<album_id>[0-9]+)',views.removeGivenAlbum,name="removegivenalbum")
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
    url(r'^api/',include('music.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
import os


class Album(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

#For every song uploaded there will be a specific path like user/album/file.mp3
def get_upload_path(instance, filename):
    #if not os.path.exists(str(instance.user.pk)+'/'+str(instance.album.album_title)):
    #    os.makedirs(str(instance.user.pk)+'/'+str(instance.album.album_title))
    return str(instance.user.pk)+'/'+str(instance.album.album_title)+'/'+str(instance.song_title)+'.mp3'

class Song(models.Model):
    user = models.ForeignKey(User,default=1, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

'''
    This models is for playlists and stores songs
'''
class Playlist(models.Model):
    user = models.ForeignKey(User,default = 1, on_delete=models.CASCADE)
    playlist_title  = models.CharField(max_length=10)
    playlist_songs = models.ManyToManyField(Song)

'''
    This model is for user and his album interests
'''
class UserAlbum(models.Model):
    user = models.ForeignKey(User,default = 1, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, default = 1, on_delete=models.CASCADE) 

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song, Playlist


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.Form):
    audio_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple':True}))


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class PlaylistForm(forms.ModelForm):
	class Meta:
		model = Playlist
		fields = ['playlist_title']

#form to rename playlist
class RenamePlaylistForm(forms.Form):
    new_playlist_title = forms.CharField(widget=forms.TextInput(attrs={'size': '40'}))

music/api/views.py
from .serializers import AlbumSerializer,SongSerializer,SongUrlSerializer
from rest_framework import generics
from music.models import Song,Album
from rest_framework import viewsets
from django.shortcuts import get_object_or_404
from rest_framework.response import Response

class AlbumsView(generics.ListAPIView):
    serializer_class = AlbumSerializer
    def get_queryset(self):
        return Album.objects.all()
class AlbumView(generics.RetrieveAPIView):
    serializer_class = AlbumSerializer
    def get_queryset(self):
        return  Album.objects.all()
class SongsView(generics.ListAPIView):
    serializer_class = SongSerializer
    def get_queryset(self):
        return Song.objects.filter(album=self.kwargs['album_id'])
class SongsUrlView(generics.ListAPIView):
    serializer_class = SongUrlSerializer
    def get_queryset(self):
        return Song.objects.filter(album=self.kwargs['album_id'])

music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404,redirect,render_to_response
from django.db.models import Q
from django.utils.datastructures import MultiValueDictKeyError
from .forms import AlbumForm, SongForm, UserForm , PlaylistForm, RenamePlaylistForm
from .models import Album, Song, Playlist, User, UserAlbum
from django.http import HttpResponseRedirect,HttpResponse
import os, sys
import shutil
AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
from mutagen import *

def create_song(request):
    form = SongForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        files = request.FILES.getlist('audio_file')
        for a in files:
            file = File(a)
            
            ''' IF the uploaded file contains any title in its tag then it takes that else it takes the uploaded file name''' 
            file_name = ''
            if 'TIT2' in file:
                if os.name =='nt':
                    file_name= str(file.tags['TIT2']).replace(":","")
                    file_name= file_name.replace(">","")
                    file_name= file_name.replace("<","")
                    file_name= file_name.replace("/","")
                    file_name= file_name.replace("-","")
                else:
                    file_name = file.tags['TIT2']
            else:
                file_name = a.name

            '''IF there isn't any data about album in the mp3 it sets it to unknown'''
            file_album_name=''
            if 'TALB' in file:
                
                file_album_name=file.tags['TALB']
            else:
                file_album_name='Unknown'
            
            '''If album is created for the first time'''
            if not Album.objects.filter(album_title=file_album_name):
                if 'APIC:' in file:
                    artwork = file.tags['APIC:'].data
                    filename='media/albums/'+str(file_album_name)+'.jpg'
                    with open(filename, 'wb+') as img:
                        img.write(artwork) # write artwork to new image
                        
                    statinfo = os.stat(filename)#gives details of the image
                    if statinfo.st_size==0:
                        '''If there is no image then we use default'''
                        filename='default.jpg'
                    else:
                        '''The below file name stores address .../..../media/filename'''
                        filename="albums/"+str(file_album_name)+'.jpg'

                new=Album(album_title=file_album_name,user=request.user,album_logo=filename)
                new.save()
        
            if not Song.objects.filter(album__album_title=file_album_name,song_title=file_name).exists():
                '''save the uploaded files to the file system and insert into database'''
                song_title=file_name
                with open(str("media/songs/"+str(song_title)+".mp3"), 'wb+') as destination:
                    for chunk in a.chunks():
                        destination.write(chunk)
                upload_url = "songs/"+str(song_title)+".mp3"
                new_song = Song(user = request.user, album = Album.objects.get(album_title=file_album_name), song_title = song_title, audio_file = upload_url)
                new_song.save()
            addGivenAlbum(request,Album.objects.get(album_title=file_album_name).id)
                    
        return JsonResponse({'success':True}) #redirects to the home page
    context = {
        'form': form,
    }
    return render(request,'music/create_song.html', context)


def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id,user=request.user)
    shutil.rmtree('media/'+str(request.user.id)+'/'+str(album.album_title))#deletes folder
    album.delete()
    albums = Album.objects.filter(user=request.user)
    return HttpResponseRedirect('/')



'''
    if the folder is deleted then redirect to home page
'''
def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id,user=request.user)
    song.delete()
    remove_song(request.user.pk,album.album_title,song.song_title)
    deleted = if_no_songs_delete_folder(request.user.pk,album.album_title,album)
    if deleted:
        return JsonResponse({'album':False})
    return JsonResponse({'album':True})


def detail(request, album_id):
        user = request.user
        l=[]
        album = get_object_or_404(Album, pk=album_id)
        songstoplay  = givesongsurl( Song.objects.filter(album=album_id))
        return render(request, 'music/detail.html', {'album': album, 'user': user, 'songstoplay':songstoplay})


def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    albums = Album.objects.all()
    songstoplay = givesongsurl(Song.objects.all())
    context = {'albums': albums,'songstoplay': songstoplay,'searched':False}
    if  request.user.is_authenticated:
        form = SongForm(request.POST or None, request.FILES or None)
        useralbums =  Album.objects.filter(id__in = UserAlbum.objects.filter(user=request.user).values_list('album',flat=True)).values_list('id',flat=True)
        context['form'] = form
        context['searched'] = False
        context['useralbums'] = useralbums
    return render(request, 'music/index.html', context)



def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/music/')
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    
    return render(request, 'music/login.html')

def givesongsurl(allsongs):
    l=[]
    for a in allsongs:
        l.append(a.audio_file.url)
    return l

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)


def songs(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        try:
            users_songs = Song.objects.all()
            #l = givesongsurl(users_songs)
            
        except Song.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
        })

'''
    if there is no mp3 file then it deletes the album and returns True. 
    if there is a mp3 file it does nothing
'''
def if_no_songs_delete_folder(usrid,albtitle,albm):
    for file in os.listdir('media/'+str(usrid)+'/'+str(albtitle)):
        if file.endswith(".mp3"):
            break
    else:
        shutil.rmtree('media/'+str(usrid)+'/'+str(albtitle))
        albm.delete()
        return True
    return False

def remove_song(usrid,albtitle,sngtitle):
    os.remove('media/'+str(usrid)+'/'+str(albtitle)+'/'+str(sngtitle)+'.mp3')
    return

def create_playlist(request):
    form = PlaylistForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            title = form.cleaned_data['playlist_title']
            if len(Playlist.objects.filter(playlist_title = title , user = request.user))==0:
                newPlaylist = Playlist(  playlist_title = title)
                newPlaylist.user = request.user
                newPlaylist.save()
                return HttpResponse('')
            else :
                context = {
                    'form':form,
                    'error':'playlist exists'
                }
                return render(request, 'music/createPlaylist.html', context)            
    context = {'form':form}
    return render(request, 'music/createPlaylist.html', context)

def playlists(request):
    user_playlists=Playlist.objects.filter(user = request.user)
    songs_in_playlist = []
    for this in user_playlists:
        songs = this.playlist_songs.all()
        songs_in_playlist.append(givesongsurl(songs))
    l=[]
    zipped = zip(user_playlists,songs_in_playlist)
    context = {

music/templates/music/addalbums.html
{% extends 'music/base.html' %}
{% block title %}ADD SONGS{% endblock %}

{% block body %}
    {% for album in albums %}
    <p>{{album.album_title}}</p>
    <a href="{% url 'music:addgivenalbum' album.id %}">add</a>
    {%endfor%}
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mahimusic{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'music/styles/index_style.css' %}"/>    
    <link href="{% static 'music/fonts.css' %}" rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'music/bootstrap.css' %}"/>    
    <script type="text/javascript">
        var music = "{% url 'music:myalbums' %}";
        var users = "{% url 'music:users' %}";
    </script>
    <script src="{% static 'music/js/jquery.js'%}"></script>
    <script src="{% static 'music/js/ajax.js' %}"></script>            
    <script src="{% static 'music/js/bootstrap.js' %}"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
    <script src="{% static 'music/js/jquery.form.min.js' %}"></script>
</head>

<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">


            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="cursor: pointer;"  id="home_button">Mahimusic</a>
            </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                {%if request.user.id%}
                <li  id="albums_button" style="cursor: pointer;"><a  ><span class="glyphicon glyphicon-cd" aria-hidden="true"></span> &nbsp; Albums</a></li>
                {%endif%}
                <li style="cursor: pointer;" id="users_button"><a ><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp; Users</a></li>
            </ul>
            <ul class="dropdown">
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                    {% csrf_token %}
                        <input type="text" name="search" id = "search" autocomplete="off">
                    </div>
                </form>
                    <!-- Content get replaced after serach query is provided -->
                <div class="dropdown-content" id="dropdown-content">    
                </div>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a id="play all" href="#" onclick="playall();return false;"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Play All</a>
                </li>
                {%if request.user.id%}
                <li>
                    <a id="addsong" href="#" onclick="startmodal();return false;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Songs</a>
                </li>
                
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                {%else%}
                <li>
                    <a href="{% url 'music:login_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login/Signup
                    </a>
                </li>
                {%endif%}
            </ul>
        </div>
        <div id="myModal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <div class="inside-modal" id="myModalcontent"></div>
                
            </div>
            <div id="status"></div>
        </div>
    </div>
</nav>
<div class="impor">
{% block body %}
{% endblock %}
</div>
<audio controls id = "audio"> <!-- One or more source files, each referencing the same audio but in a different file format. The browser will choose the first file which it is able to play. -->  You will see this text if native audio playback is not supported. <!-- You could use this fall-back feature to insert a JavaScript-based audio player. --> </audio> 

<script type="text/javascript">var listbuffer = {{songstoplay|safe}};</script>
<script src="{% static 'music/js/player.js' %}"></script>
<script type="text/javascript">
var albums_button = $("#albums_button");
var users_button = $("#users_button"); 
var home_button = $("#home_button");

function ActiveClass(butn) {
    albums_button.removeClass("active");
    users_button.removeClass("active");
    butn.addClass("active");
}
var home = "{% url 'music:index' %}";
var albums = "{% url 'music:myalbums' %}";
var users = "{% url 'music:users' %}";
home_button.click(function(){
    replace(home);
    ActiveClass(home_button);
});
albums_button.click(function () {
    replace(albums);
    ActiveClass(albums_button);
});


users_button.click(function(){
    replace(users);
    ActiveClass(users_button);
})
    var span = document.getElementsByClassName("close")[0];
    var modal = document.getElementById('myModal');

    span.onclick = function() {
        modal.style.display = "none";
    }

    function startmodal(){
        var modal = document.getElementById('myModal');
        modal.style.display = "block";
    }
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

</body>
</html>

music/templates/music/index3.html
{% extends 'music/base.html' %}

{% block body %}
<div class="impo">
<div class="albums-container container-fluid">
    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            {{artwork}}
            {% if albums %}
            <div class = "maindiv">
                <div class = "album_containers">       
                    <div class = "albums_m">
                    {% for album in albums %}
                        <div class="single_album">
                            <div class="album_logo">
                            {% url 'music:detail' album.id as link%}                                
                                <img id="myImage" src="{{ album.album_logo.url }}" class="img-responsive" onclick="replace('{{link}}')" style="cursor: pointer;">
                                <span class="text-block">
                                    <h5>{{album.album_title}}</h5>
                                </span>
                            </div>                       
                        </div>
                        {% cycle '' '' '' '' '' '' %}
                    {% endfor %}
                    </div>
                </div>
            </div>    
            {% endif %}            
        </div>   
    </div>
</div>
</div>
{% endblock %}

music/templates/music/myalbums.html
    {% extends 'music/base.html' %}

    {% block body %}
    <div class="impo">
            <script type="text/javascript">var listbuffer ={{songstoplay|safe}};</script>
    
    <div class="albums-container container-fluid">
        <!-- Albums -->
        <div class="row">
            <div class="col-sm-12">
                {{artwork}}
                {% if albums %}
                <div class = "maindiv">
                    <div class = "album_containers"> 
                            <h3>Your Albums</h3>
      
                        <div class = "albums_m">
                        {% for album in albums %}
                            <div class="single_album">
                                <div class="album_logo">
                                {% url 'music:detail' album.id as link%}                                
                                    <img id="myImage" src="{{ album.album_logo.url }}" class="img-responsive" onclick="replace('{{link}}')" style="cursor: pointer;">
                                    <span class="text-block">
                                        <h5>{{album.album_title}}</h5>   
                                    </span>
                                    <object class="playalbum" onclick="playthisalbum('{{album.id}}')"><span style="cursor: pointer;font-size:50px;color:red" class="glyphicon glyphicon-play" aria-hidden="true"></span></object>                                    
                                </div> 
                                <!--a href="{% url 'music:removegivenalbum' album.id %}">Remove</a-->
                                {% url 'music:removegivenalbum' album.id as link1%}
                                {% url 'music:myalbums'  as link2%}                                
                                <button type="button" class="btn btn-warning" onclick="addalbumscript('{{link1}}','{{link2}}')">Remove</button>
                            </div>
                            {% cycle '' '' '' '' '' '' %}
                        {% endfor %}
                        </div>
                    </div>
                </div>    
                {% endif %}            
            </div>   
        </div>
    </div>
    </div>
    {% endblock %}
    
    

music/templates/music/playlists.html
{%extends 'music/base.html'%}

{%block body%}
<script>var list = {{l|safe}};</script>
<div class="impo">
{% for a in p %}
	{{a.playlist_songs.all.0.song_title}}
{%endfor%}
<div class="container-fluid songs-container">
    <div class="row">
        <div class="col-sm-12">
            <h3><center>Playlists</center></h3>
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Play</th>
                                <th>Playlist title</th>
                                <th>Delete</th>
                                <th>Removeallsongs</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for playlist in zipped %}
                            <tr>
                                <td>
                                    <button type="button" class="btn btn-success btn-xs" onclick="playthislist({{ playlist.1 }})">
                                        <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                    </button>
                                </td>
                                <td><a href="{% url 'music:playlist' playlist.0.id %}">{{ playlist.0.playlist_title }}</a></td>
                                <td><a href="{% url 'music:deleteplaylist' playlist.0.id%}">Delete</a></td>
                                <td><a href="{% url 'music:removeallsongsfromplaylist' playlist.0.id  1 %}">remove all songs</a></td>    
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}All Songs{% endblock %}

{% block body %}
<script>var list = {{l|safe}}; </script>
<div class="impo">
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs'  %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:songs'  %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                            <button type="button" class="btn btn-success btn-xs" onclick="playthis('{{ song.audio_file.url }}')">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        {% url 'music:detail' song.album.id as link%}
                                        <div style="cursor: pointer;" onclick="replace('{{link}}')">{{ song.album.album_title }}</div>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
</div>
{% endblock %}

music/templates/music/viewuser.html
<!DOCTYPE html>
<html>
<body>
{{l}}
{%for album in albums%}
<p>
{{album}}
</p>
{%endfor%}
</body>
</html>